{{- if and (.Values.googleCloudPlatform.enableManagedCertificate) (.Values.keycloak.enabled) }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: mlaide-keycloak-cert
spec:
  domains:
  - {{ .Values.keycloak.ingress.domain }}
{{- end }}